### ISSUE TITLE
timestamp

### ISSUE THREAD

**Issue by ghost** [amsokol/go-grpc-http-rest-microservice-tutorial#7]
Hi Aleksandr,

I'm getting reminder field has invalid format ->timestamp: nil Timestamp when trying to start the client. I've tried troubleshooting this, all the code is correct and there are very few docs online.

B.

**Comment by amsokol** [comment]
Hi, could you plz add here sequence of actions how I can reproduce the error.

**Comment by ghost** [comment]
Thanks Aleksandr,
My code is here https://github.com/billyyumyum/microservice if you have the time to compile or look at  it. If you don't it's ok as I have been advancing through other means with gPRC. I know you are very busy. 
The problem is you won't be able to replicate my local MySQL setup which could be the problem (I don't know)
Thanks for making the tutorial available by the way... there's not much out there as you know...

**Comment by amsokol** [comment]
Hi, thanks. Please give me time until the end of the week.

**Comment by ghost** [comment]
No problem! Thanks

**Comment by amsokol** [comment]
Hi,

You have missed time.Timestamp to Proto Timestamp conversation in toDoServiceServer.Read method.
See here for details:
https://github.com/amsokol/go-grpc-http-rest-microservice-tutorial/blob/part1/pkg/service/v1/todo-service.go#L126

**Comment by ghost** [comment]
Thanks Aleksandr
